(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Needs["xAct`xLightCone`"]
$DebugInfoQ=True;


org[expr_]:=NoScalar@Collect[ContractMetric[expr],$PerturbationParameter,ToCanonical]
collect[expr_]:=NoScalar@Collect[expr,$PerturbationParameter,Identity]


DefManifold[M,4,{\[Alpha],\[Beta],\[Gamma],\[Mu],\[Nu],\[Lambda],\[Sigma]}]
DefMetric[-1,g[-\[Alpha],-\[Beta]],CD,{";","\[Del]"},PrintAs->"g"];


SetSlicingUpToScreenSpaceObinna[g,u,-1,h,cd,{"|","D"},n,NSS,cd2,{"|","\!\(\*SubscriptBox[\(\[Del]\), \(\[UpTee]\)]\)"},PrintAs->"N"]


DefScreenProjectedTensor[V1[-\[Nu]],NSS,PrintAs->"\!\(\*SubscriptBox[\(V\), \(\[UpTee]\)]\)"]


DefScreenProjectedTensor[T1[-\[Nu],-\[Mu]],NSS,PrintAs->"T"]



